puppetlabs/puppet-editor-services

.github/issue_template.md, .github/pull_request_template.md
This commit adds Github issue and pull request templates to this repo
=> (maint) Add issue and pull request templates

lib/puppet-languageserver/manifest/hover_provider.rb, lib/puppet-languageserver/message_router.rb
This commit resolves two minor rubocop violations.
=> (maint) Minor rubocop fixes

CHANGELOG.md, lib/puppet-editor-services/version.rb
This commit prepares the module for v0.12.0 release.
=> (maint) Prepare for 0.12.0 release

lib/puppet-debugserver.rb, lib/puppet-languageserver.rb
This commit updates the repo for minor rubocop violations.
=> (maint) Update for minor rubocop fixes

CHANGELOG.md, lib/puppet-editor-services/version.rb
=> (GH-71) Release 0.15.1

CHANGELOG.md, lib/puppet-editor-services/version.rb
This commit prepares the module for  a 0.19.0 release
=> (GH-115) Prepare for 0.19.0 release

CHANGELOG.md, lib/puppet-editor-services/version.rb
=> (GH-152) Release 0.20.0

.rubocop.yml, Rakefile, vendor/README.md, vendor/puppet-lint/.rubocop_todo.yml, vendor/puppet-lint/.travis.yml, vendor/puppet-lint/CHANGELOG.md, vendor/puppet-lint/README.md, vendor/puppet-lint/Rakefile, vendor/puppet-lint/appveyor.yml, vendor/puppet-lint/lib/puppet-lint/data.rb, vendor/puppet-lint/lib/puppet-lint/lexer.rb, vendor/puppet-lint/lib/puppet-lint/lexer/string_slurper.rb, vendor/puppet-lint/lib/puppet-lint/lexer/token.rb, vendor/puppet-lint/lib/puppet-lint/optparser.rb, vendor/puppet-lint/lib/puppet-lint/plugins/check_conditionals/case_without_default.rb, vendor/puppet-lint/lib/puppet-lint/plugins/check_resources/ensure_first_param.rb, vendor/puppet-lint/lib/puppet-lint/plugins/check_strings/quoted_booleans.rb, vendor/puppet-lint/lib/puppet-lint/plugins/check_strings/variables_not_enclosed.rb, vendor/puppet-lint/lib/puppet-lint/plugins/check_whitespace/arrow_alignment.rb, vendor/puppet-lint/lib/puppet-lint/version.rb
=> (maint) Update puppet-lint to 2.4.2

CHANGELOG.md, lib/puppet_editor_services/version.rb
This commit updates the changelog and version for the 0.24.0 release.
=> (maint) Prepare for 0.24.0 release

CHANGELOG.md, lib/puppet-languageserver-sidecar/facter_helper.rb, lib/puppet-languageserver-sidecar/puppet_modulepath_monkey_patches.rb, lib/puppet-languageserver/facter_helper.rb, lib/puppet-languageserver/manifest/completion_provider.rb, lib/puppet-languageserver/manifest/hover_provider.rb, lib/puppet-languageserver/puppet_helper.rb, lib/puppet-languageserver/puppet_helper/cache.rb, lib/puppet-languageserver/sidecar_protocol.rb, lib/puppet-languageserver/sidecar_queue.rb, lib/puppet_editor_services/version.rb, lib/puppet_languageserver_sidecar.rb, spec/debugserver/integration/puppet-debugserver/end_to_end_spec.rb, spec/languageserver-sidecar/fixtures/real_agent/cache/lib/facter/fixture_agent_custom_fact.rb, spec/languageserver-sidecar/fixtures/valid_environment_workspace/site/private/facts.d/fixture_environment_external_fact.yaml, spec/languageserver-sidecar/fixtures/valid_environment_workspace/site/private/lib/facter/fixture_environment_custom_fact.rb, spec/languageserver-sidecar/fixtures/valid_module_workspace/facts.d/fixture_module_external_fact.yaml, spec/languageserver-sidecar/fixtures/valid_module_workspace/lib/facter/fixture_module_custom_fact.rb, spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/facter_helper_spec.rb, spec/languageserver/spec_helper.rb, spec/languageserver/unit/puppet-languageserver/sidecar_protocol_spec.rb
=> (maint) Mergeback master into 1.0

.travis.yml
Allow travis to build 1.0 branch
=> (maint) Allow travis to build 1.0 branch

lib/puppet-languageserver-sidecar/facter_helper.rb, lib/puppet-languageserver-sidecar/puppet_monkey_patches.rb
This reverts commit f8e88a5b9052505de5866edefda521ccf33ab7b9.
=> Revert "(GH-238) Monkey patch Facter for minimal resets"

CHANGELOG.md, lib/lsp/lsp_custom.rb, lib/puppet-languageserver/message_handler.rb, lib/puppet-languageserver/puppetfile/validation_provider.rb, spec/languageserver/unit/puppet-languageserver/puppetfile/validation_provider_spec.rb
- (GH-256) Add puppetfile-resolver endpoint
=> (GH-256) Puppetfile dependency endpoint

CHANGELOG.md, Gemfile, lib/lsp/lsp_custom.rb, lib/puppet-languageserver/message_handler.rb, lib/puppet-languageserver/puppetfile/validation_provider.rb, lib/puppet_editor_services/version.rb, spec/languageserver/acceptance/end_to_end_spec.rb, spec/languageserver/spec_editor_client.rb, spec/languageserver/unit/puppet-languageserver/puppetfile/validation_provider_spec.rb
This PR:
* Updates 1.0 to the head of master
* Fixes one bug with the mergeup
* Prepares 1.0 to be merged back into master
=> (GH-262) Prepare 1.0 to be merged into master

.devcontainer/Dockerfile
The release process uses PowerShell to deploy the release.  This commit adds
PowerShell to the development container so releases can be done from inside the
container.
=> (maint) Add Pwsh to Dev Container

.github/workflows/release.yml, .github/workflows/release_prep.yml, .gitignore
this PR fixes a bug with release.yml to now correctly retrieve the current release version of this repo.
=> (CONT-739) - Update release.yml

Rakefile
this pr adds a "v" prefix to the version number of built artifacts.
=> (maint) - add v prefix to built artifacts

README.md
=> (CAT-1529) Update README.md LICENSE

README.md
=> (CAT-1336) - Update README

.github/workflows/release.yml
=> (maint) - Add release notes to github release

lib/puppet-languageserver-sidecar/puppet_strings_helper.rb
=> (maint) -  Rubocop fixes

.github/workflows/ci.yml, Gemfile, Rakefile, spec/debugserver/spec_debug_helper.rb, spec/languageserver-sidecar/spec_helper.rb, spec/languageserver/spec_helper.rb, spec/spec_helper.rb
"(CAT-1618) - Add code coverage to ci"
pdk version: `3.0.0`
=> pdksync - "(CAT-1618) - Add code coverage to ci"

Rakefile
=> (Dependencies) - Upgrade puppet-lint to v4.2.4 & puppet-strings to v4.1.2

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release_prep.yml
=> (CAT-2224) - Update ubuntu
