LICENSE
This commit re-adds the LICENSE file from the originating puppet-vscode
project.  The project remains an Apache 2 licensed product.
=> (maint) Re-add LICENSE file

.gitignore, CHANGELOG.md, Gemfile, Rakefile, appveyor.yml, tools/upload_release.ps1
Previously the language server resided in the same repo as the VS Code client
which meant a discrete packaging server was not required.  As this is now a
separate repo, this commit adds a rake build command to create ZIP and Tar files
of the language server.
=> (maint) Add a packaging process

README.md
Previously the README assumed only a language server and was located in the
puppet-vscode repository.  This commit updates the README with the latest
information about the language and debug servers.
=> (doc) Update README with Editor Services

CHANGELOG.md, lib/puppet-debugserver.rb, lib/puppet-debugserver/json_handler.rb, lib/puppet-debugserver/message_router.rb, lib/puppet-editor-services.rb, lib/puppet-editor-services/logging.rb, lib/puppet-editor-services/simple_base.rb, lib/puppet-editor-services/simple_stdio_server.rb, lib/puppet-editor-services/simple_tcp_server.rb, lib/puppet-languageserver.rb, lib/puppet-languageserver/json_rpc_handler.rb, lib/puppet-languageserver/message_router.rb, lib/puppet-languageserver/puppet_monkey_patches.rb, lib/puppet-languageserver/validation_queue.rb, spec/debugserver/integration/puppet-debugserver/json_handler_spec.rb, spec/languageserver/integration/puppet-languageserver/message_router_spec.rb, spec/languageserver/integration/puppet-languageserver_spec.rb, spec/languageserver/spec_helper.rb, spec/languageserver/unit/puppet-languageserver/message_router_spec.rb
Previously the different transport types, TCP and STDIO, were very closely coupled which made debugging and maintaining them difficult.  This commit changes the relationships between the server, client connection, message handler and message router classes/objects to be much looser and can therefore be defined/instantiated easier at run time;
---
A new SimpleSTDIOServer class was created which implements a blocking STDIO pipe reader.  It also implements an async stop method which be called when the Language Server wishes to exit.
---
Previously if an invalid logfile location was specified e.g. C:\ or a missing parent directory, the service (Language or Debug Server) would error.  This is undesired as a bad log file should not cause a catastrophic failure.  This commit modifies the logging …
=> (GH-11) Refactor transport layer and fix STDIO server

README.md, lib/puppet-languageserver.rb, lib/puppet-languageserver/puppet_helper.rb, lib/puppet-languageserver/puppet_helper/file_cache.rb, spec/languageserver/spec_helper.rb, spec/languageserver/unit/puppet-languageserver/puppet_helper/file_cache_spec.rb, spec/languageserver/unit/puppet-languageserver/puppet_helper_spec.rb
Previously the language server would crash if the Environment Path did not exist.
This can happen when pluginsync syncs all the files into the lib directory, or a
newly created puppet agent.  This commit changes the load behaviour to instead
check if the directory exists and just ignore it if it does not.  This commit
also adds a test for this scenario.
---
Previously the persistent file cache would crash if the temporary directory
could not be detected, or did not exist.  This commit changes the detection to
be cross platform supported and adds error detection if the cache directory
could not be created.  If the the cache directory is unable to be created all
calls to the persistent file cache then emulate as if the cache is empty thereby
still allowing the language server to operate. …
=> (GH-10)(GH-14) Fix unix loading for language server

tools/How_to_release.md
This commit adds a README on how to do a release of the
puppet editor services code.
=> (maint) Add doc on how to do a release

lib/puppet-languageserver/providers.rb, lib/puppet-languageserver/puppetfile/r10k/module/base.rb, lib/puppet-languageserver/puppetfile/r10k/module/forge.rb, lib/puppet-languageserver/puppetfile/r10k/module/git.rb, lib/puppet-languageserver/puppetfile/r10k/module/invalid.rb, lib/puppet-languageserver/puppetfile/r10k/module/local.rb, lib/puppet-languageserver/puppetfile/r10k/module/svn.rb, lib/puppet-languageserver/puppetfile/r10k/puppetfile.rb, lib/puppet-languageserver/puppetfile/validation_provider.rb, lib/puppet-languageserver/validation_queue.rb, spec/languageserver/unit/puppet-languageserver/puppetfile/validation_provider_spec.rb, spec/languageserver/unit/puppet-languageserver/validation_queue_spec.rb
Previously the language server could identify a Puppetfile file but would not
actually do anything with it.  This commit;
* Adds a basic Puppetfile parser based on the skeleton of the R10K gem
* Adds valiadation that the ruby style Puppetfile could be parsed and reports
diagnostic errors if found
* Integrates into the async validation process
* Adds unit tests for the provider
---
Previously basic validation for Puppetfile's was added.  This commit;
* Adds more detailed parsing of Puppetfile to extract different types of modules
git, local, svn or forge.  These types have enough information to identify a
module type, and basic name/title/version validation
* Adds an internal only module type called invalid which is used to track
invalid module definitions.  Without this, the validation …
=> (GH-28) Add basic puppetfile support

lib/puppet-languageserver.rb, lib/puppet-languageserver/document_store.rb, lib/puppet-languageserver/epp/validation_provider.rb, lib/puppet-languageserver/manifest/validation_provider.rb, lib/puppet-languageserver/message_router.rb, lib/puppet-languageserver/validation_queue.rb, spec/languageserver/fixtures/control_repos/valid/Puppetfile, spec/languageserver/fixtures/module_sources/valid/metadata.json, spec/languageserver/integration/puppet-languageserver/document_store_spec.rb, spec/languageserver/integration/puppet-languageserver/manifest/validation_provider_spec.rb, spec/languageserver/unit/puppet-languageserver/message_router_spec.rb, spec/languageserver/unit/puppet-languageserver/validation_queue_spec.rb
Previously the --local-workspace option was mostly ignored in the puppetfile
validation.  However this has caused problems when validating inside control
repositories which do not have a metadata.json file (instead it's Puppetfile).
This commit refactors the workspace detection out of the puppetfile validation
and moves it into the Document Store.
This commit also adds a simple timed based caching mechanism to reduce File IO
as it can be exercised vigourously when users are typing and validation is
occuring very often.  An arbitrary value of 60 seconds was chosen the TTL of the
cache.  This means that after 60 seconds the workspace will be re-evaluated to
make sure the user is still in a module (metadata.json) or control repo
(Puppetfile).
---
Now that the workspace root detection has …
=> (GH-26) Refactor workspace detection for control repos and modules

README.md, lib/puppet-debugserver.rb, lib/puppet-editor-services/simple_tcp_server.rb, lib/puppet-languageserver.rb
Previously the language and debug server used hardocoded default ports.  This
commit changes the behaviour to use automatically generated high-ports when
starting, but still honours manual port specification
This commit also updates the default hostname from 127.0.0.1 to localhost to
add support for IP6 only systems.
=> (GH-36) Use automatic port assignment as default

lib/puppet-debugserver/puppet_debug_breakpoints.rb, lib/puppet-editor-services/version.rb, lib/puppet-languageserver/crash_dump.rb, lib/puppet-languageserver/puppet_monkey_patches.rb
Previously VS Code was sending filenames in the API calls which always matched
the file system, however this is no longer the case.  This exposed a bug in the
debug adapter which depended on this behaviour. This commit modifies the line
based breakpoints to use a canonical filename.  However due to debug server
never knowing what naming scheme is coming from the editor we had to resort to
a naive method of just setting it to all lowercase.  This _may_ cause an issue
on case sensitive file systems however Puppet style guides prohibit manifest
names only changing by case.
=> (GH-31) Use canonical names for line based breakpoints

Rakefile
Previously rubocop would search child directories for its configuration file
which caused problems with Puppet-Lint as it uses an older version.  This commit
updates the rake task to only use the project config file.
=> (maint) Force rubocop to only use project config

lib/puppet-languageserver/puppet_helper.rb
Previously the puppet environment detection normally defaulted to root however
this did not work correctly when the user running the language-server was
non-root.  This commit instead updates the environment detection to correctly
find the puppet environment, and defaults to the previous behaviour if the new
method failed to work.
Fixes #46
=> (GH-46) Detect Puppet Environment correctly

lib/puppet-editor-services/simple_stdio_server.rb
Previously if the STDIN pipe was in a bad state, the pipe would appear to be
readable however when it is attempted to be read, it was throwing an EOF.  This
can occur when Javascript closes a child language server process.  This wasn't
caught in development due to the INT trap that is setup globally, so when
developers pressed Ctrl-C in the javascript parent process, the ruby child
process also saw it and terminated correctly.
Fixes #49
=> (GH-49) Exit STDIO loop if STDIN reaches EOF

.travis.yml, README.md, appveyor.yml, lib/puppet-languageserver/puppet_helper.rb, lib/puppet-languageserver/puppet_monkey_patches.rb
The Language Server was broken for Puppet 6.  This PR updates the language server for Puppet 6 support, while still supporting Puppet 4 and 5.
This PR also adds Puppet 6 to the testing matrix.
Fixes #54
=> (GH-54) Support Puppet 6 in the Language Server

CHANGELOG.md, lib/puppet-editor-services/version.rb
This commit prepares for a version 0.15.0 release.
https://github.com/lingua-pupuli/puppet-editor-services/compare/0.14.0...master
=> (maint) Prepare for 0.15.0 release

.travis.yml, appveyor.yml, lib/puppet-debugserver/puppet_debug_session.rb, spec/debugserver/integration/puppet-debugserver/end_to_end_spec.rb
The Debug Server is currently broken when using Puppet 6.  While the work to
enable the Debug Server is being undertaken, this commit adds a check which
terminates the Debug Server gracefully if it is detected on Puppet 6.  This
commit also updates the end-to-end tests to skip testing on Puppet 6.
---
Previously the Debug Server did not tests on the newly released Puppet 6.  This
commit adds Puppet 6 to the testing matrix of the Debug Server.
This commit also cleans up the Travis and Appveyor comments to be mataching and
more concise.
---
Previously each testing combination was tested in isolation.  However this meant
bundler was being called multiple times for no reasone.  Also while the
Appveyor test runtimes are quite low, because there are so many cells there's a
large delay in the …
=> (GH-55) Disable the Debug Server on Puppet 6

lib/puppet-languageserver.rb, lib/puppet-languageserver/manifest/definition_provider.rb, lib/puppet-languageserver/uri_helper.rb, spec/languageserver/unit/puppet-languageserver/uri_helper_spec.rb
Fixes #66, reported in https://github.com/lingua-pupuli/puppet-vscode/issues/331
=> (GH-66) Fix go to definition

lib/puppet-languageserver-sidecar/sidecar_protocol_extensions.rb, lib/puppet-languageserver/manifest/completion_provider.rb, lib/puppet-languageserver/sidecar_protocol.rb, spec/languageserver/integration/puppet-languageserver/manifest/completion_provider_spec.rb, spec/languageserver/spec_helper.rb, spec/languageserver/unit/puppet-languageserver/sidecar_protocol_spec.rb
Previously when a completion resolution request was received for a resource it
was hardcoded to return the name and ensure property.  However not all resources
are ensurable, and some resources have other required properties or parameters.
This commit changes the resource completion to interrogate the Puppet Type and
then generate a more appropriate code snippet;
* The sidecar was extended to also track the isnamevar? value for resource
properties and parameters. This was needed by the completion resolver as
namevars should not appear in the code snippet as they come from the resource
name.
This also required tests to changed for this new property in the sidecar
protocol.
* The resource_type completion request was modified to dynamically generate the
snippet for resources;
- If the …
=> (GH-67) Make resource completion smarter

CHANGELOG.md, lib/puppet-languageserver/manifest/completion_provider.rb
This commit adds a completion item for the `node` keyword when in the root of
a puppet manifest.  This is not applicable for Puppetfile or EPP files.
Fixed #75
=> (GH-75) Add Node completion snippet

lib/puppet-languageserver/sidecar_protocol.rb
The PuppetType serialiser needless set hash attributes that are set by the base
class. This commit removes the redundant code.
=> (maint) Remove redundant code

CHANGELOG.md, lib/puppet-languageserver-sidecar/puppet_helper.rb, lib/puppet-languageserver-sidecar/sidecar_protocol_extensions.rb, lib/puppet-languageserver/manifest/completion_provider.rb, lib/puppet-languageserver/manifest/hover_provider.rb, lib/puppet-languageserver/puppet_helper.rb, lib/puppet-languageserver/puppet_helper/cache_objects.rb, lib/puppet-languageserver/sidecar_protocol.rb, spec/languageserver-sidecar/unit/puppet-languageserver-sidecar/sidecar_protocol_extensions_spec.rb, spec/languageserver/integration/puppet-languageserver/manifest/completion_provider_spec.rb, spec/languageserver/integration/puppet-languageserver/manifest/hover_provider_spec.rb, spec/languageserver/spec_helper.rb, spec/languageserver/unit/puppet-languageserver/sidecar_protocol_spec.rb
Previously the Sidecar would only evaluate the name of Puppet Classes and
Defined Types.  This commit adds support for Puppet Class parameters;
Also updates the completion and hover provider for the new information
Fixes #34
=> (GH-34) Parse class and defined type parameters 

CHANGELOG.md, lib/puppet-languageserver/document_store.rb, lib/puppet-languageserver/message_router.rb, lib/puppet-languageserver/puppet_helper.rb, lib/puppet-languageserver/sidecar_queue.rb, lib/puppet_languageserver.rb
The Sidecar has the ability to process the active workspace for Puppet Type,
Class and Function information however this wasn't exposed in the Language
Server.  This commit;
* Modifies the Language Server loading to also queue up processing the workspace
if the workspace is a module (has metadata.json)
* Modifies the message router to process the workspace when a Puppet file (.pp)
is saved.  It will also remove any workspace classes, types and functions if
the workspace is NOT a module.  This is needed if a user removes metadata.json
during the editing session
* Also expires the document store cache on every file save to force the
workspace to be re-evaluated on document save.  This should hopefully happen
not too frequently, but still hopefully see changes to the workspace fast
enough …
=> (GH-68) Load workspace information on initial start and on document saving

lib/puppet-editor-services/version.rb
This updates the version file for the 0.16.0 release. This fixes #80 
Note, the rest of https://github.com/lingua-pupuli/puppet-editor-services/blob/master/tools/How_to_release.md needs to be followed
=> (GH-80) Release 0.16.0

lib/puppet-editor-services/version.rb
This commit corrects the version of the editor
services to `0.16.0` from `0.16.1` which was
merged due to failure of review (me).
The code is otherwise unchanged and should
be released.
=> (MAINT) Fix release version to 0.16.0

CHANGELOG.md
This commit updates the changelog to be in line with Keep a Change log format
and adds a missing issue.
=> (GH-80) Update changelog for Keep a Changelog format

README.md, lib/puppet-languageserver/puppet_helper.rb, lib/puppet-languageserver/sidecar_queue.rb, lib/puppet_languageserver.rb, lib/puppet_languageserver_sidecar.rb, spec/languageserver/spec_helper.rb
Previously some command line arguments used by the Sidecar were not present in
the Language Server, therefore they could never be used.  This commit;
* Adds the --[no-]cache, --feature-flags and --puppet-settings=TEXT settings
and modifies the Puppet Helper and Sidecar Queue to then pass these settings
along to the sidecar
* Fixes a simple typo in the Sidecar settings
* Deprecates the --enable-file-cache setting as it no longer has any effect
* Adds some logging on Language Server startup to output the puppet settings and
initializes them as early as possible
---
Fixes #35 on the Editor Services side.  An additional PR will need to be raised for the VSCode extension to pass in the `--modulepath` settings
=> (GH-35) Update Language Server command arguments to be like Sidecar

lib/languageserver/document_symbol.rb, lib/puppet-languageserver/manifest/document_symbol_provider.rb, lib/puppet-languageserver/message_router.rb, lib/puppet-languageserver/puppet_helper.rb, lib/puppet-languageserver/puppet_helper/cache.rb, lib/puppet-languageserver/server_capabilities.rb, spec/languageserver/spec_helper.rb
Fixes #88 
The object cache contains all of the type, function and class information so it
should be easily be able to be queried and then emit these results as part of a
workspace symbol request (as opposed to document symbol).  This commit adds the
provider and cache methods to support querying all objects in the cache.
=> (GH-88) Add workspace symbols provider

CHANGELOG.md, lib/puppet-editor-services/version.rb
Fixes #90 
This commit prepares the project for a 0.17.0 release.
=> (GH-90) Prepare for 0.17.0 release

.travis.yml, lib/puppet-languageserver/puppetfile/validation_provider.rb
Previously validating puppetfiles was silently failing due to;
"Error in ValidationQueue Thread: wrong number of arguments (given 1, expected 2..3)"
This commit changes the puppetfile validation method signature to mirror that of the
manifest validation provider.
=> (maint) Fix validation of puppetfiles

lib/puppet-languageserver-sidecar/puppet_monkey_patches.rb, lib/puppet-languageserver/document_store.rb, lib/puppet-languageserver/manifest/completion_provider.rb, lib/puppet-languageserver/manifest/definition_provider.rb, lib/puppet-languageserver/manifest/document_symbol_provider.rb, lib/puppet-languageserver/manifest/hover_provider.rb, lib/puppet-languageserver/manifest/validation_provider.rb, lib/puppet-languageserver/message_router.rb, lib/puppet-languageserver/puppet_monkey_patches.rb, lib/puppet-languageserver/puppet_parser_helper.rb, lib/puppet-languageserver/uri_helper.rb, lib/puppet-languageserver/validation_queue.rb, spec/languageserver/integration/puppet-languageserver/document_store_spec.rb, spec/languageserver/integration/puppet-languageserver/manifest/completion_provider_spec.rb, spec/languageserver/integration/puppet-languageserver/manifest/definition_provider_spec.rb, spec/languageserver/integration/puppet-languageserver/manifest/hover_provider_spec.rb, spec/languageserver/integration/puppet-languageserver/manifest/validation_provider_spec.rb, spec/languageserver/unit/puppet-languageserver/manifest/document_symbol_provider_spec.rb, spec/languageserver/unit/puppet-languageserver/message_router_spec.rb, spec/languageserver/unit/puppet-languageserver/uri_helper_spec.rb, spec/languageserver/unit/puppet-languageserver/validation_queue_spec.rb
The Puppet language introduced Puppet Tasks and Plans as part of
Puppet 5.4.0 [1].  A special parsing switch `--tasks` was
introduced which changes the behaviour of the Puppet parser, that
is switching it into "tasks" mode.  Unfortunately this switch is
global to all Puppet parsing therefore to dynamically switch it
like we do in Editor Services, this required a global mutex to be
used.
Note that this commit does not add Puppet Tasks/Plans intellisense
but merely allows the standard manifest providers (completion,
validation etc.) to actually function instead of silently failing
This commit;
* Modifies the Puppet parser, via monkey patching, to implement a
"singleton" parsing method that dynamically, and safely, switch
the parsing mode on a per request basis
* Modifies the Document Store …
=> (GH-24) Allow parsing in tasks mode

CHANGELOG.md, lib/puppet-editor-services/version.rb
This commit prepares Editor Serivces for a 0.18.0 release.
=> (GH-99) Prepre for 0.18.0 release

lib/puppet_languageserver_sidecar.rb
Fixes a typo when writing a sidecar file.
=> (maint) Fix typo for UTF8 file output

lib/puppet-editor-services/logging.rb, lib/puppet-languageserver/message_router.rb, lib/puppet-languageserver/sidecar_queue.rb, lib/puppet_debugserver.rb, lib/puppet_languageserver.rb, lib/puppet_languageserver_sidecar.rb
Previously it was not possible to specify which puppet gem version to use via
the command line arguments.  This commit adds a --puppet-version argument to the
language server and also the sidecar.  This commit also passes through the
puppet version from the lanugage server to the sidecar
=> (GH-111) Add --puppet-version command line argument

lib/puppet-languageserver/facter_helper.rb
Relates to #113 
Previously the facter helper had no error trapping.  Normally this isn't an
issue on Facter 3.x (Puppet Agent), however the PDK uses Facter 2.x which is
still running in the same ruby session as the Language Server.  This means that
if an error occurs then it could crash the entire language server.  This commit
wraps the facter loading in a rescue block and returns zero facts for
intellisense.
=> (GH-113) Rescue errors when running Facter 2.x

.rubocop.yml, lib/puppet-debugserver/message_router.rb, lib/puppet-debugserver/puppet_debug_session.rb, lib/puppet-debugserver/puppet_monkey_patches.rb, lib/puppet-languageserver-sidecar/puppet_helper.rb, lib/puppet-languageserver-sidecar/puppet_parser_helper.rb, lib/puppet-languageserver/epp/validation_provider.rb, lib/puppet-languageserver/facter_helper.rb, lib/puppet-languageserver/manifest/validation_provider.rb, lib/puppet-languageserver/puppet_parser_helper.rb, lib/puppet-languageserver/puppetfile/validation_provider.rb, lib/puppet-languageserver/sidecar_queue.rb, lib/puppet-languageserver/validation_queue.rb, lib/puppet_languageserver_sidecar.rb
This commit updates Editor Services for the new cops introduced in
Rubocop 0.67.1.
=> (maint) Update for rubocop errors

lib/puppet-languageserver/json_rpc_handler.rb, lib/puppet-languageserver/message_router.rb, lib/puppet-languageserver/server_capabilities.rb, lib/puppet_languageserver.rb
Fixes #118 
Previously the language server would crash/terminate early if a critical gem
like puppet was unavailable.  This can happen when the ruby environment is not
from the Puppet Agent or PDK.  This commit changes the behaviour of the
Language Server to still execute but it a completely disable fashion:
* Detects a failed gem load for critical gems and sets
PuppetLanguageServer.active? is to false
* When the Language Server is not active, a different Message Router is used
which effectively warns the user that the server failed to start and that
all functions are disabled. The server responds to the client with no
capabilities and the custom getVersion request, is responded to with
unknown data
No automated tests were added as this is an edge case.  Manual testing was
performed by …
=> (GH-118) Fail gracefully when critical gems cannot load

CHANGELOG.md, lib/puppet-editor-services/version.rb
This commit prepares the project for 0.19.1 release.
=> (maint) Prepare for 0.19.1 release

Gemfile, lib/puppet-languageserver-sidecar/cache/base.rb, lib/puppet-languageserver-sidecar/cache/filesystem.rb, lib/puppet-languageserver-sidecar/cache/null.rb, lib/puppet-languageserver-sidecar/puppet_helper_puppetstrings.rb, lib/puppet-languageserver-sidecar/puppet_modulepath_monkey_patches.rb, lib/puppet-languageserver-sidecar/puppet_monkey_patches_puppetstrings.rb, lib/puppet-languageserver-sidecar/puppet_strings_helper.rb, lib/puppet-languageserver-sidecar/puppet_strings_monkey_patches.rb, lib/puppet-languageserver/sidecar_protocol.rb, lib/puppet_languageserver_sidecar.rb, spec/languageserver-sidecar/fixtures/real_agent/cache/lib/puppet/functions/default_pup4_function.rb, spec/languageserver-sidecar/fixtures/real_agent/cache/lib/puppet/functions/environment/default_env_pup4_function.rb, spec/languageserver-sidecar/fixtures/real_agent/cache/lib/puppet/functions/modname/default_mod_pup4_function.rb, spec/languageserver-sidecar/fixtures/valid_environment_workspace/site/profile/lib/puppet/functions/badname/pup4_function.rb, spec/languageserver-sidecar/fixtures/valid_environment_workspace/site/profile/lib/puppet/functions/profile/pup4_envprofile_function.rb, spec/languageserver-sidecar/fixtures/valid_environment_workspace/site/profile/lib/puppet/functions/pup4_env_badfile.rb, spec/languageserver-sidecar/fixtures/valid_environment_workspace/site/profile/lib/puppet/functions/pup4_env_badfunction.rb, spec/languageserver-sidecar/fixtures/valid_environment_workspace/site/profile/lib/puppet/functions/pup4_env_function.rb, spec/languageserver-sidecar/fixtures/valid_module_workspace/lib/puppet/functions/badname/fixture_pup4_env_function.rb, spec/languageserver-sidecar/fixtures/valid_module_workspace/lib/puppet/functions/fixture_pup4_badfile.rb, spec/languageserver-sidecar/fixtures/valid_module_workspace/lib/puppet/functions/fixture_pup4_badfunction.rb, spec/languageserver-sidecar/fixtures/valid_module_workspace/lib/puppet/functions/fixture_pup4_function.rb, spec/languageserver-sidecar/fixtures/valid_module_workspace/lib/puppet/functions/valid/fixture_pup4_mod_function.rb, spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/featureflag_puppetstrings/featureflag_puppetstrings_spec.rb, spec/languageserver/spec_helper.rb, spec/languageserver/unit/puppet-languageserver/sidecar_protocol_spec.rb
Fixes #121 
Task 1-3 of the Puppet 4 API Project
Add a Puppet Strings feature flag - As much as possible, all code should be hidden behind this flag
Load Puppet 4 API Functions but present them as Puppet 3 functions in the Sidecar Protocol.  This preserves existing behaviour of the loading, but requires no changes to the language server itself
Use Puppet Strings (YARD) to load Puppet 4 documentation - Puppet 4 API does not use dedicated `doc` parameters, instead all documentation is provided by YARD based comments, interpretted by the Puppet-Strings gem.  Puppet Strings extends YARD to understand Puppet syntax
---
Previously the monkey patch to inject the editor workspace as a module did not
extract the module name correctly. While this was ok for older Puppet 3 API,
the Puppet 4 API …
=> (GH-121) Load Puppet Functions via Puppet API v4 and present as Puppet API v3 functions

lib/puppet-languageserver-sidecar/puppet_helper_puppetstrings.rb, lib/puppet-languageserver-sidecar/puppet_monkey_patches_puppetstrings.rb, lib/puppet-languageserver-sidecar/puppet_strings_helper.rb, lib/puppet_languageserver_sidecar.rb, spec/languageserver-sidecar/fixtures/real_agent/environments/testfixtures/modules/defaultmodule/manifests/definedtype.pp, spec/languageserver-sidecar/fixtures/real_agent/environments/testfixtures/modules/defaultmodule/manifests/init.pp, spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/featureflag_puppetstrings/featureflag_puppetstrings_spec.rb
Builds on #126 - Merged
Fixes #137
---
Now that there is a puppetstrings feature flag, we can change the loading
behaviour of the Custom Types to use the newer loader and Puppet Strings
metadata evaluation.  This commit;
* Adds Custom Types ('type') ability to the retrieve_via_puppet_strings method
* Custom Types loading isn't fully implemented like Puppet Functions are, in
particular there's no use of the Smart Paths, and the loader still uses the
old autoload methods.  To work around this a new loader is created, which is
based on the the NullLoader.  It's purpose is to only support the needed
discover_path method, however as it's a NullLoader, it won't actually load
anything if it's called by Puppet.
This loader calls the old autoloader using the same logic we used previously
but …
=> (GH-137) Load Puppet Custom Types, Defined Types and Classes via Puppet API v4

spec/languageserver/unit/puppet-languageserver/sidecar_protocol_spec.rb
This commit fixes two errors in the test description, to match what is actually
being tested.
=> (maint) Fix typo in test descriptions

lib/puppet-languageserver/puppet_helper/cache_objects.rb, spec/languageserver/unit/puppet-languageserver/puppet_helper/cache_objects_spec.rb
Previously the in-memory cache objects duplicated the object properties of the
Sidecar protocol but this is not necessary.  This commit changes the inmemory
cache object to instead inherits from the sidecar and extends it.  The
from_sidecar! method is modified to dynamically copy the object instead of
hardcoded values.
=> (maint) Refactor in-memory cache objects

lib/puppet-languageserver-sidecar/puppet_strings_helper.rb, lib/puppet-languageserver-sidecar/sidecar_protocol_extensions.rb, lib/puppet-languageserver/manifest/completion_provider.rb, lib/puppet-languageserver/manifest/hover_provider.rb, lib/puppet-languageserver/sidecar_protocol.rb, spec/languageserver-sidecar/fixtures/real_agent/cache/.gitignore, spec/languageserver-sidecar/fixtures/real_agent/environments/testfixtures/modules/defaultmodule/functions/puppetfunc.pp, spec/languageserver-sidecar/fixtures/valid_module_workspace/functions/modulefunc.pp, spec/languageserver-sidecar/fixtures/valid_module_workspace/lib/puppet/functions/fixture_pup4_function.rb, spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/featureflag_puppetstrings/featureflag_puppetstrings_spec.rb, spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/featureflag_puppetstrings/puppet_strings_helper_spec.rb, spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/puppet-languageserver-sidecar_spec.rb, spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/puppet_parser_helper_spec.rb, spec/languageserver-sidecar/unit/puppet-languageserver-sidecar/sidecar_protocol_extensions_spec.rb, spec/languageserver/integration/puppet-languageserver/manifest/completion_provider_spec.rb, spec/languageserver/spec_helper.rb, spec/languageserver/unit/puppet-languageserver/puppet_helper/cache_objects_spec.rb, spec/languageserver/unit/puppet-languageserver/sidecar_protocol_spec.rb
~~Builds on #140~~
Fixes #141
---
Previously the Sidecar Protocol had the serialisation methods on the
BasePuppetObject however this meant anything that wanted to use the
serialisation methods also inherited the parameters like key and calling_source.
This commit:
* Moves the serialisation methods (to_json, from_json!) to BaseClass which
BasePuppetObject now inherits from
* Adds equality methods on the BaseClass to make it possible to compare
Sidecar objects correctly.  This is mainly required in spec tests to test for
equality (either == or eql?)
* Adds a hash method to generate the hash number required when Sidecar objects
are put into hashtables
---
Previously the Puppet Function information retrieved over the Sidecar Protocol
only supported the older V3 Function API.  This commit …
=> (GH-141) Modify the Puppet Function loading to use all of the new Puppet 4 API features

Gemfile
Due to PDOC-283 [1] YARD needs to be pinned below 0.9.20 to pass our
integration tests. As this is only affecting a feature behind a flag, there is
no need to add a workaround.  Once puppet-strings is updated and released this
pin can be removed.
[1]https://tickets.puppetlabs.com/browse/PDOC-283
=> (maint) Pin YARD to 0.9.19

lib/puppet-languageserver/document_store.rb, lib/puppet-languageserver/message_router.rb, lib/puppet-languageserver/uri_helper.rb, lib/puppet-languageserver/validation_queue.rb, spec/languageserver/integration/puppet-languageserver/document_store_spec.rb, spec/languageserver/unit/puppet-languageserver/document_store_spec.rb, spec/languageserver/unit/puppet-languageserver/message_router_spec.rb
Fixes #127 
Fixes #128
Fixes #131
Previously Puppet Plan files had to exist within a Module however with the
Boltdir being introduced this is no longer true.  This commit updates the
detection to remove the module metadata.json requirement and use the pathname
instead.
Previously the plan detection method was called module_plan_file? however as the
module part is no longer required, the name is now plan_file?.
=>  (GH-128) Detect Puppet Plan files correctly

lib/puppet-languageserver-sidecar/puppet_parser_helper.rb
Fixes #147 
Note - Technically this doesn't fix the error, but at least Editor Services will not crashing or throw bad data.  The fact a gem is missing from the ruby environment is outside the control of Editor Services.
Previously the sidecar would error completely when a LoadError was encountered.
This could be caused by gem Facter trying to load libraries which are not
present.  StandardError does not trap these.  This commit also traps the
LoadError and allows the sidecar to return a properly formatted response to
Editor Services intead of dumping error text to STDERR.
=> (GH-147) Gracefully fail on LoadError when compiling manifests

spec/debugserver/fixtures/environments/testfixtures/manifests/kitchen_sink.pp, spec/debugserver/integration/puppet-debugserver/end_to_end_spec.rb, spec/debugserver/integration/puppet-debugserver/json_handler_spec.rb, spec/debugserver/spec_debug_client.rb, spec/debugserver/spec_debug_helper.rb
Previously the kitchen_sink tests did not actually include a test for the 'next'
command.  This commit updates the test manifest fixture with an additional class
which is 'next'-d over and adds the test for this scenario.
---
Previously the methods for impersonating a Debug Client were a cross multiple
files.  This commit consolidates the debug client helpers into a single class
and updates the tests to use this class.
=> (GH-55) Refactor Test Debug Client and add test for Next

Rakefile, vendor/README.md, vendor/puppet-lint/CHANGELOG.md, vendor/puppet-lint/appveyor.yml, vendor/puppet-lint/lib/puppet-lint/checks.rb, vendor/puppet-lint/lib/puppet-lint/plugins/check_classes/arrow_on_right_operand_line.rb, vendor/puppet-lint/lib/puppet-lint/plugins/check_whitespace/arrow_alignment.rb, vendor/puppet-lint/lib/puppet-lint/plugins/check_whitespace/trailing_whitespace.rb, vendor/puppet-lint/lib/puppet-lint/version.rb
Fixed #106
This commit updates the vendored puppet-lint gem to 2.3.6.
=> (GH-106) Update puppet-lint to 2.3.6

lib/lsp/lsp_base.rb, lib/puppet-languageserver/manifest/signature_provider.rb, lib/puppet-languageserver/message_router.rb, lib/puppet-languageserver/providers.rb, lib/puppet-languageserver/puppet_parser_helper.rb, lib/puppet-languageserver/server_capabilities.rb, spec/languageserver/integration/puppet-languageserver/manifest/signature_provider_spec.rb
Builds on #142
Fixes #144
In action
---
Previously the object_under_cursor method only returned the AST object and the
path to the object.  However some providers may also require a locator because
Puppet 4 does not expose the Locator on the AST object, only on the Factory.
This commit adds the return struct for the object_under_cursor method to also
return the Locator.
No test changes are required.
---
Previously the object_under_cursor always assumed it should remove the trigger
character when trying to figure out the object under the cursor. While this
works for things like completion and hover, it does not for signature help. This
commit updates the options hash with a new key called remove_trigger_char which
by default removes the character during detection.  Just like the default …
=> (GH-144)  Add signature help provider feature

Gemfile
This reverts commit a0fcdc174e7a40365b236202b3d37f067ad81296.
Puppet Strings 2.3.0 now works with yard 0.9.20
=> Revert "(maint) Pin YARD to 0.9.19"

spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/featureflag_puppetstrings/featureflag_puppetstrings_spec.rb
Previously the test helper was appending to the cmd_options object, which ended
up with double the parameters if it was called twice.  This commit creates a
copy of the array first, before modifying it.
=> (maint) Fix integration test

lib/puppet-languageserver/sidecar_protocol.rb, spec/languageserver/unit/puppet-languageserver/sidecar_protocol_spec.rb
Previously the Sidecar Protocol had methods to convert to and from hash however
they were never tested to ensure that they could be "round-tripped", that is
converted to a hash and then back to a sidecar object with no loss of data. This
commit adds the test and corrects any behvaiour in the protocol implementation.
=> (maint) Add tests for roundtripping hash serialisation

lib/puppet-languageserver-sidecar/puppet_helper_puppetstrings.rb, lib/puppet-languageserver-sidecar/puppet_strings_helper.rb, lib/puppet-languageserver/sidecar_protocol.rb, lib/puppet_languageserver_sidecar.rb, spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/featureflag_puppetstrings/featureflag_puppetstrings_spec.rb, spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/puppet-languageserver-sidecar_spec.rb, spec/languageserver/unit/puppet-languageserver/sidecar_protocol_spec.rb
Fixes #163 
Previously, to get all metadata information, the sidecar would need to be called
multiple times, however, with the puppetstrings featureflag, we can now evaluate
the metadata all at once.
---
This PR adds an AggregateMetadata object and two new tasks `default_aggregate` and `workspace_aggregate`
=> (GH-163) Add aggregate metadata sidecar object and tasks

lib/puppet-languageserver-sidecar/puppet_helper_puppetstrings.rb, lib/puppet-languageserver/puppet_helper.rb, lib/puppet-languageserver/puppet_helper/cache.rb, lib/puppet-languageserver/sidecar_protocol.rb, lib/puppet-languageserver/sidecar_queue.rb, lib/puppet_languageserver.rb, lib/puppet_languageserver_sidecar.rb, spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/featureflag_puppetstrings/featureflag_puppetstrings_spec.rb, spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/puppet-languageserver-sidecar_spec.rb, spec/languageserver/integration/puppet-languageserver/sidecar_queue_spec.rb
---
Previously the tests use private instance methods to verify the object, however
the each_list method now does that. This commit changes the tests to use this
method instead.
---
Previously the metadata aggregate action could only be used with the
puppetstrings feature flag.  However it is also very useful for normal operation.
This commit changes the action to be valid, and adds tests for this scenario.
---
This commit changes the language server to use the default and workspace
aggregate actions, but behind the puppetstrings feature.  There are no test
changes required.
=> (GH-163) Use aggregate metadata actions for puppetstrings feature flag

lib/lsp/lsp_base.rb, lib/lsp/lsp_protocol.rb, lib/puppet-languageserver/json_rpc_handler.rb, lib/puppet-languageserver/message_router.rb, spec/languageserver/spec_helper.rb, spec/languageserver/unit/puppet-languageserver/json_rpc_handler_spec.rb, spec/languageserver/unit/puppet-languageserver/message_router_spec.rb, tools/lsp_introspect/index.js
Fixes #169
Previously the LSP introspection tool used ruby frozen strings. However rubocop
prefers the `frozen_string_literal: true` header.  This commit changes the
introspection script and updates the lsp ruby files.
---
Previously the ruby classes created by the LSP introspection could create
methods which are reserved in ruby, but not JavaScript.  This commit modifies
the introspection tool to munge reserved method names with the suffix "__lsp"
so that they can still be used in ruby but the JSON serialisation and
deserialisation still work for the protocol.
---
Previously the JSON Handler could only handle LSP Notifications and Requests,
however the can also be a Server to Client Request Response workflow.
This commit:
* Updates the JSON Handler to record JSON requests from the server …
=> (maint)(GH-169) Fixes to adhere to Language Server Protocol

lib/puppet-languageserver-sidecar/puppet_helper_puppetstrings.rb, lib/puppet-languageserver-sidecar/puppet_strings_helper.rb, lib/puppet-languageserver/manifest/hover_provider.rb, lib/puppet-languageserver/puppet_helper.rb, lib/puppet-languageserver/puppet_helper/cache.rb, lib/puppet-languageserver/sidecar_protocol.rb, lib/puppet-languageserver/sidecar_queue.rb, lib/puppet_languageserver.rb, lib/puppet_languageserver_sidecar.rb, spec/languageserver-sidecar/fixtures/real_agent/cache/lib/puppet/datatypes/cachedatatype.rb, spec/languageserver-sidecar/fixtures/real_agent/environments/testfixtures/modules/defaultmodule/types/moduletypealias.pp, spec/languageserver-sidecar/fixtures/valid_environment_workspace/site/profile/lib/puppet/datatypes/profile_data_type.rb, spec/languageserver-sidecar/fixtures/valid_environment_workspace/site/role/types/testtype.pp, spec/languageserver-sidecar/fixtures/valid_module_workspace/lib/puppet/datatypes/valid_module_data_type.rb, spec/languageserver-sidecar/fixtures/valid_module_workspace/types/testtype.pp, spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/featureflag_puppetstrings/featureflag_puppetstrings_spec.rb, spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/featureflag_puppetstrings/puppet_strings_helper_spec.rb, spec/languageserver/integration/puppet-languageserver/manifest/hover_provider_spec.rb, spec/languageserver/spec_helper.rb, spec/languageserver/unit/puppet-languageserver/sidecar_protocol_spec.rb
Fixes #174 
Now that Puppet Strings understands Puppet Data Types, the sidecar can be
modified to query for them.  This commit:
* Updates the Sidecar Protocol to add Puppet DataTypes and DataType aliases
* Adds two new actions default_datatypes and workspace_datatypes. Note that
these will only be populated if the puppetstrings feature flag is set.
* Updates the Puppet Strings helper to extract the data type info from the YARD
objects
* Updates the retrieve_via_puppet_strings method to also be able to extract
Puppet Data Types.
* Unfortunately there is no way to enumerate all of the "core" data types.
As a workaround, we _can_ query the type factory class and instantiate all of
the types the factory can produce.  While not perfect, it's a very good start.
---
Now that the sidecar can …
=> (GH-174) Understand Puppet Data Types

lib/puppet-languageserver/manifest/completion_provider.rb, spec/languageserver/unit/puppet-languageserver/manifest/completion_provider_spec.rb
Fixes #181 
Added Completion for [resource-like class declare](https://puppet.com/docs/puppet/5.3/lang_classes.html#using-resource-like-declarations)
=> Added completion for resource-like class

lib/puppet-languageserver/language_client.rb, lib/puppet-languageserver/message_router.rb, spec/languageserver/unit/puppet-languageserver/language_client_spec.rb, spec/languageserver/unit/puppet-languageserver/message_router_spec.rb
Part of the work for #177 
---
Previously capability registrations were assumed to only have one possible
reqeuest per method however this isn't true.  Also the request ID is needed in
order to unregister a capability.  This commit;
* Modifies the Language Client to track registrations that are in progress and
have completed
* Now processes error messages so that registration tracking can fail tracked
registrations
* Adds tests for these scenarios
---
Previously the message router was passed in as a method parameter however as
almost all methods require the message router, this commit changes the
initializer to pass in the message router at object create time.
---
Previously client capabilities could be dynamically registered.  This commit
adds the logic and track to dynamically …
=> (GH-177) Dynamically unregister capabilities

lib/puppet-languageserver/language_client.rb, lib/puppet-languageserver/message_router.rb, lib/puppet-languageserver/server_capabilities.rb, spec/languageserver/unit/puppet-languageserver/language_client_spec.rb, spec/languageserver/unit/puppet-languageserver/message_router_spec.rb
Part of the work for #177 
Builds on #184
---
Previously the settings were passed directly from the response into the
client for processing however this does not emulate the legacy settings hash.
This commit adds the original scope onto the settings hash so it appears like
the legacy hash e.g. puppet.editorservices.abc instead of editorserivces.abc
---
While technically the protocol does allow the server to send window/showMessage
notifcations during initialization, it's better to send the warning at the
end of initialization i.e. at the initialized notification.
9d13ba8
---
Now that the Language Client can process client settings, and dynamic
registrations it is now possible to setup the server to register to receive the
onTypeFormatting request.  This commit:
* Responds to the …
=> (GH-177) Add registrations and settings for on type formatting

lib/puppet-languageserver/language_client.rb, lib/puppet-languageserver/manifest/format_on_type_provider.rb, lib/puppet-languageserver/message_router.rb, lib/puppet-languageserver/providers.rb, lib/puppet-languageserver/server_capabilities.rb, spec/languageserver/unit/puppet-languageserver/language_client_spec.rb, spec/languageserver/unit/puppet-languageserver/manifest/format_on_type_provider_spec.rb, spec/languageserver/unit/puppet-languageserver/message_router_spec.rb
Builds on #185 
Fixes #177 
---
Previously the onTypeFormatting provider was created and responds to client
settings, turning it on and off appropriately.  This commit actually adds the
on type formatter:
* Only for puppet manifests (.pp)
* Uses puppet-lint lexer to tokenise the document and uses the tokens to
determine indenting
* Will not operate if the document is over 4KB in size or the client is using
tabs instead of spaces
* Adds tests for the formatting
---
=> (GH-177) Add auto-align hash rocket feature

CHANGELOG.md, lib/puppet-editor-services/version.rb
Fixes #187 
This commit updates the changelog and version for the 0.22.0 release.
=> (GH-187) Prepare for 0.22.0 release

lib/puppet-debugserver/debug_session/hook_handlers.rb, lib/puppet-languageserver-sidecar/puppet_monkey_patches_puppetstrings.rb, spec/debugserver/integration/puppet-debugserver/end_to_end_spec.rb
Fixes #199
The Null Loader was removed in Puppet 6.11.0+ (and friends).  This commit monkey
patches the Null Loader back in if it doesn't exist.
=> (GH-199) Monkey Patch the Null Loader

lib/puppet-languageserver/manifest/format_on_type_provider.rb, spec/languageserver/unit/puppet-languageserver/manifest/format_on_type_provider_spec.rb
Fixes #201 
Multi-resource declarations [1] are delimited by semi-colons as well as being
inside a hash block.  This commit modifies the hashrocket detection to also
take into account semi-colons and adds a test for this scenario.
[1] https://puppet.com/docs/puppet/latest/style_guide.html#multiple-resources
=> (GH-201) Fix hashrocket alignment in multi-resource declarations

lib/puppet-languageserver/manifest/completion_provider.rb, lib/puppet-languageserver/message_handler.rb, spec/languageserver/integration/puppet-languageserver/manifest/completion_provider_spec.rb, spec/languageserver/unit/puppet-languageserver/message_handler_spec.rb
Fixes #139 
Previously the manifest completion provider would not provide results if the
cursor was in a defined type. This commit adds the ResourceTypeDefinition much
like the HostClassDefinition.
Previously the completion provider blindly moved the cursor one place back which
worked fine if completions were triggered by a character instead of manual.
Now that the LSP has provisions for the context of the completion request we
can intelligently figure out when to remove the trigger character.
This commit updates the mesasge handler to pass through the CompletionContext
object and the completion provider can then determine how to use the context
accordingly.  This commit also updates the tests for this behaviour.
=> (GH-139) Provide completions for defined types

.rubocop.yml, Gemfile, lib/puppet-debugserver/debug_session/hook_handlers.rb, lib/puppet-languageserver-sidecar/puppet_modulepath_monkey_patches.rb, lib/puppet-languageserver/crash_dump.rb, lib/puppet-languageserver/manifest/validation_provider.rb, lib/puppet-languageserver/message_handler.rb, lib/puppet_editor_services/server/stdio.rb, lib/puppet_editor_services/server/tcp.rb
This commit updates the project for Rubocop 0.77.0
Due to there being so many differences in rubocop for Ruby < 2.3.0, this commit
also stops bundling rubocop for old Ruby versions.
=> (maint) Update for Rubocop 0.77.0

CHANGELOG.md, lib/puppet_editor_services/version.rb
This commit updates the changelog and version for the 0.23.0 release.
=> (maint) Prepare for 0.23.0 release

lib/puppet-languageserver-sidecar/facter_helper.rb, lib/puppet-languageserver-sidecar/puppet_modulepath_monkey_patches.rb, lib/puppet-languageserver/sidecar_protocol.rb, lib/puppet_languageserver_sidecar.rb, spec/languageserver-sidecar/fixtures/real_agent/cache/lib/facter/fixture_agent_custom_fact.rb, spec/languageserver-sidecar/fixtures/valid_environment_workspace/site/private/facts.d/fixture_environment_external_fact.yaml, spec/languageserver-sidecar/fixtures/valid_environment_workspace/site/private/lib/facter/fixture_environment_custom_fact.rb, spec/languageserver-sidecar/fixtures/valid_module_workspace/facts.d/fixture_module_external_fact.yaml, spec/languageserver-sidecar/fixtures/valid_module_workspace/lib/facter/fixture_module_custom_fact.rb, spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/facter_helper_spec.rb, spec/languageserver/unit/puppet-languageserver/sidecar_protocol_spec.rb
This is part 1 of #213 .  Part2 will contain the work to actually use the sidecar to get the facts.
Previously the facts where evaluated only within the Editor Service process
however this meant the workspace couldn't be injected.  This commit adds a new
action to the Sidecar process to evaluate the facts. The Sidecar has the
required monkey patches to inject the workspace into the fact search
directories.
This commit also adds tests and fixtures to ensure that custom and external
facts can be resolved.
=> (GH-213) Gather facts using the Sidecar

spec/debugserver/integration/puppet-debugserver/end_to_end_spec.rb
Relates to #199 
Previously in commit 074ad0bc52 the stack trace handlers were modified for
Puppet 6.11.0.  That same change is now seen in Puppet 5.5.18.  This commit
modifies the test detection to also detect Puppet 5.5.18+.
=> (GH-199) Update stack trace tests for Puppet 5.5.18

lib/puppet-languageserver-sidecar/facter_helper.rb, lib/puppet-languageserver/facter_helper.rb, lib/puppet-languageserver/manifest/completion_provider.rb, lib/puppet-languageserver/manifest/hover_provider.rb, lib/puppet-languageserver/puppet_helper.rb, lib/puppet-languageserver/puppet_helper/cache.rb, lib/puppet-languageserver/sidecar_protocol.rb, lib/puppet-languageserver/sidecar_queue.rb, spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/facter_helper_spec.rb, spec/languageserver/spec_helper.rb, spec/languageserver/unit/puppet-languageserver/sidecar_protocol_spec.rb
Fixes #213 
#213 Part 2
---
Previously in commit 590804e the Sidecar was updated to retrieve facts
however the object module was incorrectly setup to be used by the Language
Server in-memory cache. This commit changes the protocol to have a Fact and
FactList, similar to PuppetClass etc.
---
Now that facts can be loaded from the Sidecar, the FacterHelper needs to be
updated to use these instead of calling Facter directly.  This commit:
* Modifies the FacterHelper to call the sidecar queue to get the Fact
information
* Modifies the FacterHelper to expose methods to query facts
* Updates the cache to store facts
* Updates the tests for the new Fact collection method
=> (GH-213) Use Facts from the Sidecar

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, lib/lsp/lsp_custom.rb, lib/puppet-languageserver-sidecar/puppet_parser_helper.rb, lib/puppet-languageserver-sidecar/sidecar_protocol_extensions.rb, lib/puppet-languageserver/message_handler.rb, lib/puppet-languageserver/sidecar_protocol.rb, lib/puppet-languageserver/sidecar_queue.rb, lib/puppet_languageserver_sidecar.rb, spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/featureflag_puppetstrings/featureflag_puppetstrings_spec.rb, spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/puppet-languageserver-sidecar_spec.rb, spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/puppet_helper_spec.rb, spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/puppet_parser_helper_spec.rb, spec/languageserver-sidecar/unit/puppet-languageserver-sidecar/sidecar_protocol_extensions_spec.rb, spec/languageserver/unit/puppet-languageserver/message_handler_spec.rb, spec/languageserver/unit/puppet-languageserver/sidecar_protocol_spec.rb
This removes the dot graph implementation and replaces it with an object that contains all the edges and vertices from the compiled node graph.
This is used by the newer client implementation using the cytoscape library in https://github.com/lingua-pupuli/puppet-vscode/pull/614.
Fixes #221
=> (GH-221) Puppet Node Graph Response

lib/puppet-languageserver/manifest/hover_provider.rb, spec/languageserver/integration/puppet-languageserver/manifest/hover_provider_spec.rb
Fixes #207 
Previously the hover provider ignored qualified names like '::foo::bar`.  This
commit updates the Hover Provider to allow QualifedNames but use what the name
is of during processing.  This commit also adds tests for this scenario.
=> (GH-207) Allow Qualified Resource Names in hover provider

.travis.yml, Rakefile, appveyor.yml, spec/languageserver/acceptance/end_to_end_spec.rb, spec/languageserver/fixtures/end_to_end_manifest.pp, spec/languageserver/spec_editor_client.rb, spec/languageserver/spec_helper.rb
This commit adds basic acceptance tests, using an emulated Language Client to
send messages to the Language Server under test. Currently only a single file
is tested.  Later commits will add testing when in a Module or Control Repo.
=> (GH-168) Add acceptance tests

.rubocop.yml, Gemfile
(maint) Update rubocop to 0.80.x
=> (maint) Update rubocop to 0.80.x

lib/puppet-languageserver-sidecar/facter_helper.rb, lib/puppet-languageserver-sidecar/puppet_monkey_patches.rb
Closes #238
It appears that Facter 4.0.16 is resetting the Facter search dirs
which then causes the sidecar to not find some external or custom facts.
This commit monkey patches the Facter module and makes it possible
to limit the number of resets to one.
=> (GH-238) Monkey patch Facter for minimal resets

CHANGELOG.md, lib/lsp/lsp_custom.rb, lib/puppet-languageserver/message_handler.rb, lib/puppet-languageserver/puppet_helper.rb, lib/puppet-languageserver/sidecar_queue.rb, lib/puppet_languageserver_sidecar.rb, spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/facter_helper_spec.rb
This PR adds a new endpoint that returns puppet facts from the current environment
This PR supports https://github.com/puppetlabs/puppet-vscode/issues/631
Fixes #242
=> GH 242 facts endpoint

lib/puppet-languageserver/facter_helper.rb, lib/puppet-languageserver/message_handler.rb, lib/puppet-languageserver/puppet_helper.rb, lib/puppet-languageserver/sidecar_queue.rb, lib/puppet_languageserver_sidecar.rb, spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/facter_helper_spec.rb, spec/languageserver/acceptance/end_to_end_spec.rb, spec/languageserver/spec_editor_client.rb
Fixes #245 
This commit adds an acceptance test for the puppet/getFacts request. Previously
this message was added to the message handler, but not to the test suite.
---
Previously the puppet/getFacts request would call out to Facter directly however
this can be very slow, particularly with Facter v2 in the PDK.  This commit
changes the request to instead use the object cache which already has all of the
available facter information.
This commit also moves the method from the PuppetHelper to the FacterHelper
where it would make more sense.  This is tested as part of the acceptance suite.
---
Now that the language server no longer calls the facts_all action, the
supporting code can be removed.
=> (GH-245) Use object cache for fact data

Gemfile
Due to https://github.com/rubocop-hq/rubocop/issues/8008 this commit pins
rubocop to 0.83.0 until the fix is release in 0.85.0.
=> (maint) Pin Rubocop to < 0.84.0

README.md, Rakefile, lib/puppet-debugserver/puppet_debug_session.rb
This commit documents:
* Dropping Puppet 4 support
* Removing experimental warning for the debug server
=> (maint) Document removal of Puppet 4

Rakefile, vendor/README.md
This commit updates Puppetfile Resolver to 0.3.0.
=> (maint) Update Puppetfile Resolver to 0.3.0

lib/puppet-languageserver/manifest/document_symbol_provider.rb, lib/puppet-languageserver/manifest/validation_provider.rb
Previously in commit fed22c2 the document symbol provider was updated
to use the new LSP classes however it appears some code branches were missed.
This commit updates the document symbol provider to use the correct method name.
---
Previously the Puppet-Lint configuration could raise an error, thereby stopping
any puppet lint rules from working.  This was due to puppet-lint.rc files
containing command params which were invalide due to puppet-lint plugin gems
not being loaded e.g. --no-trailing_comma-check
This commit changes the document validator to use the default configuration if
an error occurs loading the configuration.
=> (GH-272) Puppet Lint and document symbol sometimes not working

CHANGELOG.md
Fixes #274 
This commit prepares for a 1.0.0 release.
=> (GH-274) Release 1.0.0

CHANGELOG.md, lib/puppet_editor_services/version.rb
This commit prepares Puppet Editor Services for 1.0.1 release
=> (GH-279) Prepare for 1.0.1 release

.travis.yml, appveyor.yml, lib/puppet-languageserver-sidecar/puppet_strings_helper.rb, spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/puppet-languageserver-sidecar_spec.rb
Fixes #282 
When querying with Puppet7/Ruby 2.7 it's possibe for yard to return a docstring
with no tags at all.  Previously this was an empty array but now it may also be
nil.  This commit adds a guard to only enumerate the array if it is not nil.
This commit adds Puppet 7 to the test CI matrix now that it has been released.
=> (GH-282) Add Puppet 7 to CI testing 

lib/puppet-languageserver/manifest/validation_provider.rb, spec/languageserver/integration/puppet-languageserver/manifest/validation_provider_spec.rb
Fixes #189 
Previously after a call to fix_validation_errors, many validation errors came
in as hints not errors.  This was due to PuppetLint not resetting the
`PuppetLint.configuration.fix` setting between calls.  This commit updates the
validation provider to reset this setting each call.  This commit also adds
tests for this scenario.
=> (GH-189) Reset PuppetLint configuration for each call

lib/puppet-languageserver/manifest/format_on_type_provider.rb, lib/puppet-languageserver/message_handler.rb, lib/puppet-languageserver/session_state/language_client.rb, spec/languageserver/unit/puppet-languageserver/message_handler_spec.rb
Fixes #289 
Previously only files that were less than 4KB in size could use the
format-on-type feature. This commit updates the Language Server to honor a
new configuration setting puppet.editorService.formatOnType.maxFileSize which
will determine the maximum file size.  A size of 0 will disable the size check.
The default is 4096 as per the previous behaviour.
No specific tests have been added and has been manually tested.
=> (GH-289) Make Format On Type file size configurable

lib/puppet-languageserver/manifest/validation_provider.rb
Previously in commit c70511b9 validation was changed to initialise Puppet Lint
correctly, however there was a typo in the provider.  This commit fixes the
typo and references the correct variable.
=> (GH-189) Fix module root for validation

README.md, spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/facter_helper_spec.rb
Fixes #298 
The facter 4.0.52 gem uses FFI to retrieve the legacy hostname fact. However as
FFI wasn't available it was breaking the integration tests. This commit changes
the expected fact name, from a legacy fact to a modern fact which should not
ever be removed (facterversion).
=> (GH-298) Fix tests for Facter 4.0.52 gem

.github/workflows/create-test-matrix.ps1
Ruby 2.5.9 has ASLR enabled by default and has caused some issues in the Puppet
gem (segfaults).  This commit pins Ruby to 2.5.8 to allow testing to continue.
=> (maint) Pin GitHub Action Ruby to 2.5.8

lib/puppet-languageserver/manifest/hover_provider.rb, lib/puppet-languageserver/message_handler.rb, spec/languageserver/integration/puppet-languageserver/manifest/hover_provider_spec.rb, spec/languageserver/unit/puppet-languageserver/message_handler_spec.rb
Fixes #300 
Previously, the hover provider would return a Hover object with null contents
which is not allowed by the Language Server Protocol.  This commit updates
Editor Services to instead return nil when an error occurs during the resolution.
=> (GH-300) Return nil for bad hover requests

.devcontainer/devcontainer.json
This commit explicitly adds port 9000 as a port that can be used during
development.  That way the editor services can be run inside the docker
container and VSCode can connect to it over TCP Port 9000.
=> (maint) Add port 9000 for dev. container

lib/puppet-languageserver/manifest/folding_provider.rb, lib/puppet-languageserver/message_handler.rb, lib/puppet-languageserver/providers.rb, lib/puppet-languageserver/puppet_lexer_helper.rb, lib/puppet-languageserver/server_capabilities.rb, lib/puppet-languageserver/session_state/document_store.rb, lib/puppet-languageserver/session_state/language_client.rb, lib/puppet_languageserver.rb, spec/languageserver/unit/puppet-languageserver/manifest/folding_provider_spec.rb, spec/languageserver/unit/puppet-languageserver/message_handler_spec.rb, spec/languageserver/unit/puppet-languageserver/session_state/document_store_spec.rb, spec/languageserver/unit/puppet-languageserver/session_state/language_client_spec.rb
Fixes #306 
Previously the Puppet Lexer ignored whitespace and comments and did not generate
any token information. This meant it could not be used for code formatting
purposes. This commit adds a new lexer which sub-classes the original and emits
tokens for comments. Later commits can use this lexer for operations like code
folding and as-you-type formatting.
This commit also memoizes the tokens in the document store so documents do not
need to be lexed multiple times for the same version.
---
Previously the Language Server dod not provide code folding hints, and the
client was left to use its defauly, typically indentation based.  This commit:
* Adds a manifest folding provider, which can extract code folding regions based
on block comments, multiline comments and blocks of code ( { -> …
=> (GH-306) Add a syntax aware code folding provider

lib/puppet-languageserver-sidecar/puppet_environment_monkey_patches.rb, lib/puppet_languageserver.rb
Changes with how Puppet includes Facter as suggested in the ticket means that we need to explicitly include the library.
=> (GH-311) Explicitly require Facter

README.md
This incorporates the fixes from @mrolli in #316 and also makes a few more tweaks.
=> (MAINT) Fix URLs to Puppet docs in README

README.md
The deep links into the documentation actually occur twice. This fixes
the second and additionally adjusts the os name from MacOSX to macOS.
Sorry for having overseen this in the last PR.
=> Fix second occurence of links to documentation

lib/puppet-languageserver-sidecar/puppet_strings_helper.rb
FYI when ran against our codebase LSP fails with error
```
A, [2022-01-18T12:35:46.485073 #31693]   ANY -- : SidecarQueue Thread: Calling sidecar with --action workspace_aggregate --local-workspace ~/.git/puppet --puppet-version=6.21.1 returned exitcode 1, ~/.git/puppet-editor-services/lib/puppet-languages
erver-sidecar/puppet_strings_helper.rb:147:in `block (3 levels) in populate_classes_from_yard_registry!': undefined method `join' for nil:NilClass (NoMethodError)
from ~/.git/puppet-editor-services/lib/puppet-languageserver-sidecar/puppet_strings_helper.rb:143:in `each'
from ~/.git/puppet-editor-services/lib/puppet-languageserver-sidecar/puppet_strings_helper.rb:143:in `block (2 levels) in populate_classes_from_yard_registry!'
from …
```
=> Fix `NoMethodError` in puppet_strings_helper.rb

.github/workflows/create-test-matrix.ps1
Prior to this commit testing ran on older version of puppet and ruby.
This commit removes old versions that tests are running on.
=> (maint) Removal of Puppet 5 and Puppet 6 testing

.github/workflows/create-test-matrix.ps1, puppet-languageserver
Solving a load depenencies bug.
Issue: https://github.com/puppetlabs/puppet-editor-services/issues/318
P.S.: Sorry if I'm doing something wrong. I'm not a Ruby developer and rarely commit in OpenSource projects.
=> GH-318 Used a realpath for load dependencies.

.github/workflows/release.yml
prior to this pr, artifacts were incorrectly left out of the release process.
this pr corrects this and ensures the built artifacts are uploaded with the release.
=> (maint) - add artifacts to release process

.github/workflows/ci.yml, .github/workflows/create-test-matrix.ps1, .github/workflows/nightly.yml, .github/workflows/release_prep.yml, Gemfile
Prior to this commit, deprecation warnings were present in the github actions workflows. This commit updates checkout@v2 to v3 and updates set-output to use the $GITHUB_OUTPUT environment variable
=> (CONT-988) Address deprecation warnings

.github/workflows/ci.yml, .github/workflows/nightly.yml
The deprecation warning for actions/upload-artifact@v2 was missed in the previous PR. This PR updates this to remove the deprecation warning for the workflow.
=> (CONT-988) Update actions/upload-artifact version

Gemfile
Updating to be consistent with version of ffi gem pulled in by puppet runtime. https://github.com/puppetlabs/puppet/pull/9112/files
=> (maint) - Pin ffi to 1.15.5

lib/puppet-languageserver/global_queues/validation_queue.rb, lib/puppet-languageserver/message_handler.rb, lib/puppet-languageserver/session_state/document_store.rb, spec/languageserver/unit/puppet-languageserver/global_queues/validation_queue_spec.rb
Prior to this PR, diagnostics (or "problems") in the vscode problems pane would not be removed on the closing of a file. This is bad practice, and quickly leads to a polluted problems pane with linting issues etc showing for all files despite being open or not.
This PR aims to fix this issue, by calling publishDiagnostics in the vscode API on the close of a text document with an empty array of diagnostics as per the vscode documentation.
This has been verified as working in local vscode setup.
**Before**
**After**
Fixes https://github.com/puppetlabs/puppet-editor-services/issues/357
=> (CAT-1595) - Remove diagnostic on textDoucment onDidClose

docs/architecture/decisions/0001-aggregate-file-definitions.md, lib/puppet-languageserver-sidecar/puppet_helper.rb
This PR opts to aggregate and write the file type definitions to a tempfile rather than a file within the language servers root dir.
This was causing issues with the github runners for CI, and it is also a more elegant solution.
=> (maint) - Write file type definitions to tempfile

CODEOWNERS, Gemfile
This reverts commit 4515c9d025ad3fdba5edc1e0f2541d76709eb776.
This also reverts the subsequent commit 18efae6eb1b333b412ec19f008913bf1f5fe3b2a. 
This issue has been since fixed upstream in puppet, so we can now remove these pins and the ffi gem.
=> Revert "(MAINT) - TEMP pin to FFI 1.15.2" and REVERT "(maint) - Pin ffi to 1.15.5"

lib/puppet-languageserver/manifest/completion_provider.rb
Prior to this PR, we would return completion items without a trailing comma. A trailing comma is the suggested style as per the puppet code docs, so we should append this to the returned value.
=> (CAT-1669) - Add trailing comma to completion item

Gemfile, lib/puppet-debugserver/debug_session/hook_handlers.rb, lib/puppet-debugserver/puppet_debug_session.rb, lib/puppet-languageserver/global_queues/sidecar_queue.rb, lib/puppet-languageserver/global_queues/validation_queue.rb, lib/puppet-languageserver/message_handler.rb, lib/puppet-languageserver/session_state/object_cache.rb, lib/puppet-languageserver/sidecar_protocol.rb, lib/puppet_editor_services/protocol/debug_adapter.rb, lib/puppet_editor_services/protocol/debug_adapter_messages.rb, lib/puppet_editor_services/protocol/json_rpc.rb, lib/puppet_editor_services/protocol/json_rpc_messages.rb, lib/puppet_editor_services/server/tcp.rb
Reverts puppetlabs/puppet-editor-services#380
=> Revert "(maint) Exclude breaking rubocop versions"

.gitignore, bin/puppet-debugserver, bin/puppet-languageserver, bin/puppet-languageserver-sidecar, puppet-editor-services.gemspec
This PR adds a gemspec and executables that would be called from it. The three executables are variations of the same files that reside in the root of the repo.
The idea here is to make it easier for people like myself to install a local copy of puppet-editor-services. This will facilitate easier use as a language server in things like neovim. Additionally, my hope is to use this gem as the basis for a [Nix package](https://nixos.org/manual/nixpkgs/stable/#packaging-applications) that I would maintain.
I do imagine that some more specific requirements could be added to the runtime dependencies listed in the gemspec - if you have feedback on that, I am happy to adjust.
I didn't do the check list because I didn't do any changes to the code, this is just setting up packaging.
=> Create a gem for puppet-editor-services

.github/workflows/gem_release.yml
Add a workflow to allow this to be automatically released as a gem to take advantage of: https://github.com/puppetlabs/puppet-editor-services/pull/382
=> (maint) Add gem release workflow

Gemfile
Following the latest release of the json gem, the tests have broken as a result of a change in behaviour. This commit aims to pin the json version to the last know working point.
=> (MAINT) Pin json gem after newest release
